apiVersion: v1
kind: Pod
metadata:
  name: k8s-demo-pod
  labels:
    name: k8s-demo
    author: ananth
spec:
  containers:
  - name: k8s-demo-app
    image: ananthrs/hello-k8s:latest
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "10Mi"
        cpu: "3m"
      limits:
        memory: "100Mi"
        cpu: "10m"
